# pytorch_lightning==1.7.2
seed_everything: 1
trainer:
  sync_batchnorm: true
  max_epochs: 150
  precision: 16
  gradient_clip_algorithm: norm
  gradient_clip_val: 10
model:
  num_points: 2048
  tokenizer_num_groups: 128
  tokenizer_group_size: 32
  encoder_unfreeze_epoch: 100
  encoder_dim: 384
  encoder_depth: 12
  encoder_heads: 6
  encoder_dropout: 0.1
  encoder_attention_dropout: 0.05
  encoder_drop_path_rate: 0.2
  encoder_add_pos_at_every_layer: true
  cls_head: mlp
  cls_head_dim: 256
  cls_head_dropout: 0.5
  cls_head_pooling: mean+max # mean+max+cls_token, mean+max, mean, max, cls_token
  loss_label_smoothing: 0.2
  learning_rate: 0.001
  optimizer_adamw_weight_decay: 0.05
  lr_scheduler_linear_warmup_epochs: 10
  lr_scheduler_linear_warmup_start_lr: 1.0e-06
  lr_scheduler_cosine_eta_min: 1.0e-06
  pretrained_ckpt_path: null
  train_transformations:
  - scale
  - center
  - unit_sphere
  - rotate
  val_transformations:
  - center
  - unit_sphere
  transformation_scale_min: 0.9
  transformation_scale_max: 1.1
  transformation_scale_symmetries: [1, 0, 1]
  transformation_rotate_dims: [1]
  transformation_rotate_degs: null
  transformation_translate: 0.2
  transformation_height_normalize_dim: 1
  log_tsne: false
  log_confusion_matrix: false

data:
  class_path: pointjepa.datasets.ScanObjectNNDataModule
  init_args:
    data_dir: ../../../mnt/disk2/Data/misc_ayumus/ScanObjectNN
    split: main_split
    perturbed: true
    batch_size: 32
